trigger: none

#resources:
#  pipelines:
#  - pipeline: pipelineresource
#    project: CommunityModules
#    source: SamplePlayer3_macos
#    trigger:
#      branches:
#      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# CMake
# Build with the CMake cross-platform build system

- task: CMake@1
  inputs:
    cmakeArgs: '../JeffMcClintock/SamplePlayer3'

#TODO : some kind of variable for build type: Debug/Release

- task: CMake@1
  inputs:
    cmakeArgs: '--build . --config Release'

- task: CmdLine@2
  displayName: 'Run Unit Tests'
  inputs:
    script: 'ctest --verbose -C Release -T test'
    workingDirectory: 'build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Windows Modules'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'c5461b5f-8816-4d6b-842e-7e4e5aee0627'
    pipeline: '21'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'sampleplayer3_mac'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**\build\**\*.sem'
    TargetFolder: '$(build.artifactstagingdirectory)/sampleplayer3_mac/SamplePlayerSfz.sem/Contents/x86_64-win/'
    flattenFolders: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/sampleplayer3.zip'
    replaceExistingArchive: true

- task: FtpUpload@1
  displayName: 'FTP Upload: Modules'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://ftp.synthedit.com'
    username: '$(ftp_username)'
    password: '$(ftp_password)'
    rootDirectory: '$(build.artifactstagingdirectory)'
    filePatterns: '*.zip'
    remoteDirectory: 'domains/synthedit.com/public_html/modules'
    trustSSL: true