name: Build (macOS)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload macOS modules
        uses: actions/upload-artifact@v4
        with:
          name: modules_mac
          path: |
            build/**/*.sem
            build/**/*.gmpi
          if-no-files-found: error
